media:
  input: src/content/posts/_images
  output: /images

content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts/blog
    filename: '{year}-{month}-{day}-{title}.md'
    fields:
      - name: title
        type: string
        required: true
      - name: description
        type: string
      - name: published
        type: date
        required: true
      - name: updated
        type: date
      - name: tags
        type: list
      - name: draft
        type: boolean
        default: false
      - name: pin
        type: number
        default: 0
      - name: body
        type: rich-text
        required: true
    view:
      fields: [title, published, tags]
      primary: title
      sort: [published]
      layout: list
