media: src/content/posts/_images

content:
  - name: posts
    label: Posts
    type: collection
    path: "src/content/posts/blog"
    view:
      fields: [title, published, draft]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: published
        label: Published Date
        type: date
      - name: updated
        label: Updated Date
        type: date
      - name: tags
        label: Tags
        type: string
        list:
          min: 1
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: pin
        label: Pin Priority
        type: number
        default: 0
      - name: body
        label: Body
        type: rich-text
